name: Linter 

on:
  pull_request:
    branches: [main]

jobs:
   Linter:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: github/super-linter@v4
          env:
            VALIDATE_ALL_CODEBASE: false 
            DEFAULT_BRANCH: master
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}